apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::574689675289:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1BCGBLNGNH3XZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::574689675289:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-22T00:46:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1885"
  uid: 757194cb-18de-4cdb-88f8-e1b57b9a6ba8
